### ISSUE TITLE
Is the FastLog can inference?

### ISSUE THREAD

**Issue by raftaria** [zhipeng-cai/FastLog#1]
Hello. I want to use FastLog in my private project.

so can I get Inference code? I need some assist about log.

Thanks.

**Comment by zhipeng-cai** [comment]
Hello. You can get the inference code in the src folder.
And I have provided replication instructions in the README.md

You can combine the following inference codes to utilize FastLog:

1. Run src/stage1_predict.py to predict the logging positions.

2. Run src/stage2_predict.py to generate the logging statements for the predicted logging positions obtained in Stage-1.

3. Run src/insert_log.py to insert the generated logging statements into the corresponding predicted logging positions.

**Comment by raftaria** [comment]
predict files are exists for that. 

thank you.
