### ISSUE TITLE
Invalid requirements.txt

### ISSUE THREAD

**Issue by satorukano** [zhipeng-cai/FastLog#2]
Hello. I want to use Fast Log, but following the instructions in the README, I cannot install the libraries. When looking at the contents of requirements.txt, the file appears to be intended for conda, not for pip. Would you teach me how to install the necessary libraries ?

**Comment by zhipeng-cai** [comment]
you can list the packages with their required version in the requirements.txt, and then use the command 'pip install -r requirements.txt' to install the necessary libraries.

**Comment by satorukano** [comment]
I can install packages.
Thank you.
